<?php
/* ===================================================================
   includes/bud-data.php   —   GENERATED FILE, DO NOT EDIT BY HAND

   Built from destinations-merged.xlsx. Edit the workbook and rebuild;
   anything typed straight in here is lost on the next rebuild.

   Read by api/bud-context.php, which turns it into the grounding text
   Bud is given with every message.

   Amounts and durations are STRINGS, not numbers, and ranges are kept
   as ranges: "P120-180", "2-3hrs". The source data is genuinely that
   imprecise, and flattening a range to one number would invent a
   precision nobody measured.

   NOTHING HERE IS VERIFIED. Every figure came from a worksheet whose
   notes say "published guides", "historical rate", "confirm current
   2026 rate". Bud is instructed to hedge on all of it. When the
   Tourism Office confirms a figure, mark it in the workbook and
   rebuild.
   =================================================================== */

return [
  'destinations' => [
    [
      'name' => 'Taba Taba Beach Resort',
      'town' => 'Basud',
      'budget_low' => 'P200-P400',
      'budget_high' => 'P500-P1,000+',
      'best_months' => 'March–May',
      'guide' => 'No',
      'permit' => 'No',
      'booking' => 'Yes',
      'hours' => 'No verified official operating hours published online.',
      'notes' => 'The destination is described as suitable for day trips and overnight camping.',
      'routes' => [
        [
          'origin' => 'Daet, Camarines Norte',
          'leg' => '1',
          'mode' => 'Motorcycle / private vehicle',
          'fare' => '20-30 min',
        ],
        [
          'origin' => 'Basud town area → Brgy. Taba-Taba',
          'leg' => '2',
          'mode' => 'Motorcycle / tricycle / private vehicle',
        ],
        [
          'origin' => 'Barangay Taba-Taba → Taba-Taba Beach',
          'leg' => '3',
          'mode' => 'Local road / private vehicle / motorcycle',
        ],
      ],
      'fees' => [
        [
          'label' => 'Beach entrance',
          'unit' => 'per person',
        ],
        [
          'label' => 'Cottage / hut',
          'unit' => 'Per cottage',
        ],
        [
          'label' => 'Camping',
          'unit' => 'Per tent/night or group',
        ],
        [
          'label' => 'Overnight accommodation',
          'unit' => 'Per night',
        ],
        [
          'label' => 'Parking',
          'unit' => 'Per vehicle',
        ],
        [
          'label' => 'Other activities/rentals',
          'unit' => 'Varies',
        ],
      ],
      'contacts' => [
        [
          'org' => 'local beach operator',
          'phone' => '0919 662 2038',
          'facebook' => 'facebook.com/tabatababeachresort',
        ],
        [
          'org' => 'Office of the Mayor / LGU Basud',
          'phone' => '(054) 359-0753 / 443-1017',
          'email' => 'lgubasud16@gmail.com',
          'facebook' => 'facebook.com/profile.php?id=61563281673069',
        ],
      ],
    ],
    [
      'name' => 'La Maestra Campsite and Resort',
      'town' => 'Basud',
      'best_months' => 'March–May',
      'booking' => 'Yes',
      'notes' => 'The attraction is currently categorized as a campground, suggesting that camping/outdoor recreation is a principal use. Current facilities, accommodation types, entrance fees, and camping rules should be confirmed directly before traveling.',
      'routes' => [
        [
          'origin' => 'Daet, Camarines Norte',
          'leg' => '1',
          'mode' => 'Private vehicle / motorcycle',
          'notes' => 'Travel toward Basud/Oliva. Exact travel time depends on the starting location, road conditions, and weather.',
        ],
        [
          'origin' => 'Basud Poblacion',
          'leg' => '2',
          'mode' => 'Tricycle / motorcycle / private vehicle',
          'notes' => 'Proceed toward Brgy. Oliva; confirm the final access route locally.',
        ],
        [
          'origin' => 'Oliva, Basud',
          'leg' => '3',
          'mode' => 'Local vehicle / motorcycle',
          'notes' => 'Destination is listed at 2X6W+J89, Oliva, Basud, Camarines Norte.',
        ],
      ],
    ],
    [
      'name' => 'Shrine of the Black Nazarene',
      'town' => 'Capalonga',
      'budget_low' => 'P300-P500',
      'budget_high' => 'P1,000-P1,500',
      'best_months' => 'May 12–13',
      'guide' => 'No',
      'permit' => 'No',
      'booking' => 'No',
      'hours' => 'Church is accessible 24 hours daily, but visitors should rely on the Mass schedule for planned worship. The parish office is listed as Tuesday–Sunday, 9:00 AM–12:00 NN and 2:00–5:00 PM; closed Mondays and holidays in the parish directory. Mon–Thu: 5:00–6:00 PM; Fri: 7:00–8:00 AM, 9:30–10:30 AM, 12:00–1:00 PM, 5:00–6:00 PM; Sat: 7:00–8:00 AM; Sun: 7:00–8:00 AM, 9:30–10:30 AM, 11:00 AM–12:00 NN, 5:00–6:00 PM',
      'notes' => 'This is a pilgrimage/religious site, so visitors should dress respectfully and observe Mass/church rules. The shrine becomes extremely busy around May 12–13.',
      'routes' => [
        [
          'origin' => 'Daet, Camarines Norte',
          'leg' => '1',
          'mode' => 'Bus / van',
          'time' => '2 + 0-10',
          'fare' => '120-180',
          'notes' => 'Current route information estimates approximately 2 hours and ₱120–₱180. Older local travel guides also report approximately 2 hours.',
        ],
        [
          'origin' => 'Daet → Capalonga',
          'leg' => '1',
          'mode' => 'Private car',
          'time' => '1 + 9-15 minutes',
          'fare' => 'Not per person',
          'notes' => 'Driving distance is approximately 75–76 km; current route estimates give about 1 hr 9 min.',
        ],
        [
          'origin' => 'Capalonga town/terminal → Shrine',
          'leg' => '2',
          'mode' => 'Tricycle / walking / local vehicle',
          'time' => '5-15 minutes',
          'notes' => 'The shrine is in Poblacion on Vinzon Ave., near the municipal center. Confirm the local tricycle fare before riding.',
        ],
      ],
      'fees' => [
        [
          'label' => 'Church/shrine entrance',
          'amount' => 'P0',
          'unit' => 'Per person',
          'notes' => 'No regular entrance fee.',
        ],
        [
          'label' => 'Mass attendance',
          'amount' => 'P0',
          'unit' => 'Per person',
          'notes' => 'Attendance at Mass is not presented as a paid attraction.',
        ],
        [
          'label' => 'Donation/offering',
          'amount' => 'Voluntary',
          'unit' => 'Per person',
          'notes' => 'Amount is at the visitor\'s discretion.',
        ],
        [
          'label' => 'Candles / devotional items',
          'amount' => 'P30 to P200',
          'unit' => 'per item',
          'notes' => 'Prices vary by item and current parish stock',
        ],
        [
          'label' => 'Religious oil / souvenirs',
          'amount' => 'P50 to P300',
          'unit' => 'per item',
          'notes' => 'Prices vary by item and current parish stock.',
        ],
        [
          'label' => 'Special parish services',
          'unit' => 'per service',
          'notes' => 'Coordinate directly with parish office.',
        ],
      ],
      'contacts' => [
        [
          'org' => 'Diocesan Shrine of Jesus the Black Nazarene of Capalonga / Parish of St. Lucy, Virgin and Martyr',
          'phone' => '+63 917-390-9802 +63 999-938-7619 0920 928 8167',
          'email' => 'jesusbnc2009@gmail.com',
          'facebook' => 'facebook.com/blacknazareneofcapalonga',
        ],
      ],
    ],
    [
      'name' => 'Pulong Guijanlo',
      'town' => 'Capalonga',
      'budget_low' => 'P500-P800',
      'budget_high' => 'P1,200-P2,000',
      'best_months' => 'March–May',
      'guide' => 'No',
      'permit' => 'No',
      'booking' => 'Yes',
      'hours' => 'Access depends on boat availability, tides and sea/weather conditions.',
      'notes' => 'The island is described as isolated and undeveloped, with no food stalls/facilities in published travel guides. Bring sufficient food and drinking water. Camping is possible, but visitors should bring their own tent and supplies. There is also no cellular signal reported on the island in one travel account.',
      'routes' => [
        [
          'origin' => 'Daet, Camarines Norte',
          'leg' => '1',
          'mode' => 'Bus/van',
          'time' => '2h 10m',
          'fare' => 'P120-P180',
          'notes' => 'Current route information gives approximately 2 hours from Daet to Capalonga. Actual fare should be checked at the terminal.',
        ],
        [
          'origin' => 'Capalonga town',
          'leg' => '2',
          'mode' => 'Tricycle/local transport',
          'time' => '10-30 minutes',
          'fare' => 'P30',
          'notes' => 'Travel toward the Baywalk / boat pickup area.',
        ],
        [
          'origin' => 'Capalonga Baywalk → Pulong Guijanlo',
          'leg' => '3',
          'mode' => 'Boat',
          'time' => '30 minutes',
          'fare' => 'P100',
          'notes' => 'A first-person Capalonga guide reports approximately 30 minutes by boat to Pulong Guijanlo.',
        ],
      ],
      'fees' => [
        [
          'label' => 'Island entrance',
        ],
        [
          'label' => 'Boat to Pulong Guijanlo',
        ],
        [
          'label' => 'Environmental/local fee',
          'notes' => 'Confirm with Capalonga Tourism Office before visiting.',
        ],
        [
          'label' => 'Food/water',
          'amount' => 'Bring your own',
          'notes' => 'Published guides say the island has no food stalls/facilities.',
        ],
      ],
      'contacts' => [
        [
          'org' => 'Municipality of Capalonga / Capalonga Tourism Office',
          'phone' => '0962 175 4431',
          'email' => 'camarinesnortecapalonga@gmail.com',
          'facebook' => 'facebook.com/newlgucapalonga',
        ],
      ],
    ],
    [
      'name' => 'Bagasbas Beach',
      'town' => 'Daet',
      'budget_low' => 'P300-P500',
      'budget_high' => 'P1,000-P1,500+',
      'best_months' => 'September–May',
      'guide' => 'No',
      'permit' => 'No',
      'booking' => 'No',
      'hours' => 'Public beach; current map listing shows 24 hours daily. For safety, daylight hours are preferable for ordinary swimming/beach activities.',
      'notes' => 'Bagasbas is a 5-km gray-sand beach and a major surfing destination. Its sandy seabed makes it suitable for beginners, but the Pacific-facing beach can have strong waves/currents. Visitors should follow local surf and swimming safety instructions.',
      'routes' => [
        [
          'origin' => 'Daet Town Proper',
          'leg' => '1',
          'mode' => 'Tricycle',
          'time' => '10–15 min',
          'fare' => 'P30-P40 one way',
          'notes' => 'Current/relatively recent travel guides give approximately ₱30–₱35 and 10–15 minutes.',
        ],
        [
          'origin' => 'Daet Town Proper',
          'leg' => '1',
          'mode' => 'Private vehicle/motorcycle',
          'time' => '~10–15 min',
          'notes' => 'Follow Bagasbas Road/Daet Airport Road toward Barangay Bagasbas.',
        ],
      ],
      'fees' => [
        [
          'label' => 'Beach entrance',
          'amount' => 'P0',
          'unit' => 'Per person',
          'asof' => 'Current public-beach status',
          'notes' => 'Bagasbas is a public beach.',
        ],
        [
          'label' => 'Surfing lesson',
          'amount' => 'P400',
          'unit' => 'Per person / 1 hour',
          'asof' => 'Sept. 11, 2024 source',
          'notes' => 'Latest DOT-published standard lesson price found.',
        ],
        [
          'label' => 'Advanced surfing lesson',
          'amount' => 'P4000',
          'unit' => 'Per person / 10 hours',
          'asof' => 'Sept. 11, 2024 source',
          'notes' => 'Latest DOT-published package found.',
        ],
        [
          'label' => 'Cottage',
          'amount' => '250 500 to 250-1,500',
          'unit' => 'Per cottage/night',
          'notes' => 'Rates vary by cottage/operator; confirm before booking.',
        ],
        [
          'label' => 'Surfboard rental without lesson',
          'unit' => 'Per board/time',
          'notes' => 'Confirm directly with the surf school.',
        ],
        [
          'label' => 'Parking',
          'unit' => 'Per vehicle',
          'notes' => 'Confirm locally.',
        ],
      ],
      'contacts' => [
        [
          'org' => 'Bagasbas Surfers Club Inc.',
          'phone' => '+63 915 202 8577',
          'email' => 'bagasbassurferclubinc@gmail.com',
          'facebook' => 'facebook.com/BagasbasSurfersClubInc',
        ],
      ],
    ],
    [
      'name' => 'First Rizal Monument',
      'town' => 'Daet',
      'budget_low' => 'P100-P250',
      'budget_high' => 'P300-P600',
      'best_months' => 'November–April',
      'guide' => 'No',
      'permit' => 'No',
      'booking' => 'No',
      'hours' => 'The monument is located in Rizal Park/Rizal Mini Park, which is listed as an open public par',
      'notes' => 'The monument was unveiled on December 30, 1898 and is recognized by the NHCP as a national historical landmark. It is a three-tiered stone pylon, not a statue of Rizal. The former Daet Municipal Hall/Daet Heritage Center is directly across from it.',
      'routes' => [
        [
          'origin' => 'Daet Integrated Bus Terminal',
          'leg' => '1',
          'mode' => 'Tricycle',
          'time' => '15 mins',
          'fare' => 'P30-P50',
          'notes' => 'Ride toward Rizal Mini Park / First Rizal Monument. Fare can vary depending on whether the tricycle is shared or chartered.',
        ],
        [
          'origin' => 'Daet town proper',
          'leg' => '1',
          'mode' => 'Tricycle / walking',
          'time' => '5–15 min',
          'fare' => 'P30-P50',
          'notes' => 'Tell the driver “First Rizal Monument” or “Rizal Park, Daet.” The monument is at the intersection around Magallanes/Justo Lukban and across from the former Daet Municipal Hall. Take a tricycle and tell the driver to bring you to the First Rizal Monument.',
        ],
      ],
      'fees' => [
        [
          'label' => 'Viewing First Rizal Monument',
          'amount' => 'P0',
          'unit' => 'Per person',
          'notes' => 'No entrance fee found.',
        ],
        [
          'label' => 'Rizal Mini Park',
          'amount' => 'P0',
          'unit' => 'Per person',
          'notes' => 'Public park area.',
        ],
        [
          'label' => 'Tricycle from terminal',
          'amount' => 'P30 to P50',
          'unit' => 'Per person/ride',
          'notes' => 'Fare can vary according to passenger arrangement and distance.',
        ],
      ],
      'contacts' => [
        [
          'org' => 'Camarines Norte Provincial Tourism Operations Division',
          'phone' => '0939 487 3708',
          'email' => 'cometocamnorte@gmail.com',
          'facebook' => 'facebook.com/CamNorteTourism',
        ],
      ],
    ],
    [
      'name' => 'Turayog View Deck',
      'town' => 'Jose Panganiban',
      'budget_low' => 'P500',
      'budget_high' => 'P800',
      'best_months' => 'April-May',
      'guide' => 'No',
      'permit' => 'No',
      'booking' => 'no',
      'hours' => 'Always open',
      'notes' => 'The gradient is high',
      'routes' => [
        [
          'origin' => 'Daet-Panganiban',
          'leg' => '1',
          'mode' => 'Van/Bus',
          'time' => '2-3hrs + 30',
          'fare' => '100-300',
        ],
        [
          'origin' => 'Panganiban-Turayog',
          'leg' => '1',
          'mode' => 'Tricycle/Private Car',
          'time' => '30m',
          'fare' => '300-500',
          'notes' => 'Special trip to turayog means too high price',
        ],
        [
          'origin' => 'Daet-Turayog',
          'leg' => '1',
          'mode' => 'Private Car',
          'time' => '1-2hrs + 30',
          'notes' => 'Better Option',
        ],
      ],
      'fees' => [
        [
          'label' => 'Environmental fee',
          'amount' => '20-100 to P300',
          'unit' => 'per person',
          'asof' => '2026-08-21',
          'notes' => 'depends on that day',
        ],
        [
          'label' => 'Parking',
          'amount' => '50-100',
          'unit' => 'per vehicle',
          'asof' => '2026-08-21',
        ],
      ],
      'contacts' => [
        [
          'org' => 'Jose Panganiban',
          'facebook' => 'https://www.facebook.com/profile.php?id=61568113830387',
        ],
        [
          'org' => 'Jose Panganiban',
          'phone' => '09166877978',
          'facebook' => 'PUBLIC INFORMATION OFFICE - JOSE PANGANIBAN ON FB',
        ],
      ],
    ],
    [
      'name' => 'Parola Island',
      'town' => 'Jose Panganiban',
      'budget_low' => 'P1,000-P1,500',
      'budget_high' => 'P4000',
      'best_months' => 'April-June',
      'guide' => 'yes',
      'permit' => 'yes',
      'booking' => 'Yes',
      'hours' => 'Boats do not sail in rough weather',
      'notes' => 'Limited Electricity, Mobile Signal is limited, sea conditons changes',
      'routes' => [
        [
          'origin' => 'Daet-Panganiban',
          'leg' => '1',
          'mode' => 'Van/Bus',
          'time' => '2-3hrs + 30',
          'fare' => '100-300',
          'notes' => 'Last Trip in bus/van is 4:30 - 5:30',
        ],
        [
          'origin' => 'Daet-Larap port',
          'leg' => '1',
          'mode' => 'Tricycle',
          'time' => '15-30',
          'fare' => '20-100',
        ],
        [
          'origin' => 'Larap Port-Parola',
          'leg' => '1',
          'mode' => 'Boat',
          'time' => '30mins-1hr',
        ],
        [
          'origin' => 'Jose Panganiban waterfront',
          'leg' => '1',
          'mode' => 'Boat',
          'time' => '1h',
          'notes' => 'Historical visitor trip: departed around 8 AM; approximately 60-minute boat ride in flat-sea conditions. Boat capacity reported up to 30 passengers.',
        ],
        [
          'origin' => 'Larap Port / Jose Panganiban mainland',
          'leg' => '1',
          'mode' => 'Boat',
          'time' => '1h',
          'notes' => 'Published travel guides identify Larap Port as the departure area for Parola Island.',
        ],
        [
          'origin' => 'Daet',
          'leg' => '1',
          'mode' => 'Bus/van',
          'time' => '1h',
          'fare' => 'P35-P100',
          'notes' => 'Published guides give roughly 1 hour from Daet to Jose Panganiban, with older fares around ₱35–₱100. Current fare should be checked at the terminal.',
        ],
        [
          'origin' => 'Jose Panganiban town',
          'leg' => '2',
          'mode' => 'Tricycle',
          'fare' => 'P30',
          'notes' => 'Travel toward the designated boat departure point/Larap Port. Confirm exact port with Tourism Office.',
        ],
        [
          'origin' => 'Port',
          'leg' => '3',
          'mode' => 'Boat',
          'time' => '1h',
          'fare' => 'P4000',
          'notes' => 'Weather-dependent.',
        ],
      ],
      'fees' => [
        [
          'notes' => 'If you are a solo traveler or just a small group, you may join the package tours to Parola Island offered by the tourism office or ask the tourism office to merge you with other groups to save cost. The overnight package trip cost per person is as follows: P2,200/person from Jose Panganiban (minimum of of 12 guests) P2,500/person from Daet (minimum of of 12 guests) Inclusions: – Port fee – Environmental fee – Boat transfer – 3 buffet meals at Parola Island – 1 plated meal at Turayog Resort – Resort entrance fees – Life jacket – Unli cocktail drinks (mobile) – Land transfers from port to Turayog and Bulalacao Beach',
        ],
        [
          'label' => 'Parola Island entrance',
          'amount' => 'P25',
          'unit' => 'Per person',
          'notes' => 'For Jose Panganiban residents. Confirm current 2026 rate.',
        ],
        [
          'label' => 'Parola Island entrance',
          'amount' => 'P50',
          'unit' => 'Per person',
          'asof' => 'Historical published rate',
          'notes' => 'For visitors/non-residents. Confirm current 2026 rate.',
        ],
        [
          'label' => 'Parola Island boat',
          'amount' => 'P4,000 starting',
          'unit' => 'Per boat',
          'asof' => 'Historical published rate',
          'notes' => 'Boat reported to accommodate approximately 30–40 passengers.',
        ],
        [
          'label' => 'All-inclusive package from Jose Panganiban',
          'amount' => 'P2200',
          'unit' => 'Per person',
          'asof' => 'Historical published rate',
          'notes' => 'Minimum 12 guests. Includes boat/food and other components according to published package.',
        ],
        [
          'label' => 'All-inclusive package from Daet',
          'amount' => 'P2500',
          'unit' => 'Per person',
          'asof' => 'Historical published rate',
          'notes' => 'Minimum 12 guests.',
        ],
        [
          'label' => 'Environmental/other fees',
          'notes' => 'May be incorporated into a tour package; confirm with Tourism Office.',
        ],
      ],
      'contacts' => [
        [
          'org' => 'Jose Panganiban',
          'phone' => '09166877978',
          'facebook' => 'PUBLIC INFORMATION OFFICE - JOSE PANGANIBAN ON FB',
        ],
        [
          'org' => 'Jose Panganiban',
          'phone' => '09162416149, 09703228735, 09682927079, 09852612453',
          'facebook' => 'Sofia Isabel, Ave Maria De Pena Fracia, Lady Erica on fb',
        ],
        [
          'org' => 'Jose Panganiban Municipal Tourism Office / LGU Jose Panganiban',
          'phone' => '0963-025-9024',
          'email' => 'tourismjpang@gmail.com',
          'facebook' => 'facebook.com/profile.php?id=61568113830387',
        ],
      ],
    ],
    [
      'name' => 'Malatap Falls',
      'town' => 'Labo',
      'budget_low' => 'P1000',
      'best_months' => 'April-June',
      'guide' => 'no',
      'permit' => 'no',
      'booking' => 'no',
      'hours' => 'always open',
      'notes' => 'Limited Electricity, Mobile Signal is limited, sea conditons changes',
      'routes' => [
        [
          'origin' => 'Daet - Malatap',
          'leg' => '1',
          'mode' => 'Jeep',
          'time' => '1:30hrs - 2hrs + 15',
          'fare' => '90 -100',
          'notes' => 'Last trip of jeep is 5:30',
        ],
        [
          'origin' => 'Malatap-Malatap Falls',
          'leg' => '1',
          'mode' => 'walk',
          'time' => '15mins',
        ],
      ],
      'fees' => [
        [
          'label' => 'Environmental fee',
          'amount' => '20-30',
          'unit' => 'per person',
          'asof' => '2026-02-09',
        ],
      ],
    ],
    [
      'name' => 'Tulis Peak, Mt. Bagacay',
      'town' => 'Labo',
      'budget_low' => 'P500',
      'budget_high' => 'P1000',
      'best_months' => 'March to May',
      'guide' => 'yes',
      'permit' => 'yes',
      'booking' => 'yes',
      'hours' => 'Expected until 4',
      'notes' => 'Mt. Bagacay is roughly 780m. Hikers register at the barangay hall at the jump-off and arrange a guide there. Trails to the summit are not well established.',
      'routes' => [
        [
          'origin' => 'Daet-Labo',
          'leg' => '1',
          'mode' => 'Jeep/Bus/Van',
          'time' => '30-40mins',
          'fare' => '30-40',
          'notes' => 'Last Trip is 7pm',
        ],
        [
          'origin' => 'Labo- jump off brgy. fundado',
          'leg' => '1',
          'mode' => 'Tricycle',
          'time' => '15-20mins',
          'fare' => '20-30',
          'notes' => 'There is no tricycle at night',
        ],
        [
          'origin' => 'Fundado - tulis peak',
          'mode' => 'walk/hike',
          'time' => '2-3hrs + 30',
        ],
      ],
    ],
    [
      'name' => 'Canimog Island',
      'town' => 'Mercedes',
      'budget_low' => 'P2000',
      'best_months' => 'April-June',
      'guide' => 'yes',
      'permit' => 'yes',
      'booking' => 'no',
      'hours' => 'when you get boat to get there',
      'notes' => 'No electricity, Bring your own water and powerbank',
      'routes' => [
        [
          'origin' => 'Daet-Merces',
          'mode' => 'jeepney',
          'time' => '30 - 40mins',
          'fare' => '20-25',
        ],
        [
          'origin' => 'mercedes - canimog',
          'leg' => '1',
          'mode' => 'boat',
          'time' => '1:30hrs - 2hrs + 30mins',
          'fare' => 'rent',
        ],
      ],
    ],
    [
      'name' => 'Pebble Beach',
      'town' => 'Mercedes',
      'best_months' => 'April-June',
      'guide' => 'No',
      'permit' => 'no',
      'booking' => 'yes',
      'hours' => 'open',
    ],
    [
      'name' => 'Macolabo Island',
      'town' => 'Paracale',
    ],
    [
      'name' => 'Gumaus Beach',
      'town' => 'Paracale',
    ],
    [
      'name' => 'Nacali Falls',
      'town' => 'San Lorenzo Ruiz',
      'best_months' => 'April-June',
    ],
    [
      'name' => 'Mampili River',
      'town' => 'San Lorenzo Ruiz',
    ],
    [
      'name' => 'Mananap Falls',
      'town' => 'San Vicente',
    ],
    [
      'name' => 'Mananap Falls ATV Adventure',
      'town' => 'San Vicente',
    ],
    [
      'name' => 'Busay Falls',
      'town' => 'Santa Elena',
    ],
    [
      'name' => 'Del Moro Park',
      'town' => 'Santa Elena',
    ],
    [
      'name' => 'Mangrove Eco Tourism Park',
      'town' => 'Talisay',
      'budget_low' => 'P1000',
      'budget_high' => 'P2000',
      'best_months' => 'January to September',
      'guide' => 'it depends',
      'permit' => 'No',
      'booking' => 'No',
      'hours' => 'nights',
      'notes' => 'Bring your own water',
      'routes' => [
        [
          'origin' => 'Daet',
          'leg' => '4',
          'mode' => 'Tricycle',
          'time' => '50m',
          'fare' => 'P50',
          'notes' => 'Last trip of tricycle in San Narciso Talisay is 5pm',
        ],
        [
          'origin' => 'Daet',
          'leg' => '1',
          'mode' => 'Motorcycle Private',
          'time' => '30h',
        ],
        [
          'origin' => 'Daet',
          'leg' => '1',
          'mode' => 'Jeep - Tricycle',
          'time' => '1h',
          'fare' => 'P35',
          'notes' => 'Daet Terminal to Talisay Tricycle Terminal',
        ],
      ],
      'fees' => [
        [
          'label' => 'Entrance Fee',
          'amount' => 'P10',
          'unit' => 'per person',
          'asof' => '2026-09-03',
        ],
        [
          'label' => 'Paddle to palate adventure',
          'amount' => 'P699',
          'unit' => 'per person',
          'asof' => '2026-09-03',
        ],
      ],
      'contacts' => [
        [
          'org' => 'Talisay Municipal Tourism Office',
          'phone' => '0961 588 8216',
          'email' => 'lgutalisay2019@gmail.com',
          'facebook' => 'https://www.facebook.com/p/Talisay-Tourism-Culture-Arts-Office-100063569121524/',
        ],
      ],
    ],
    [
      'name' => 'St. Francis of Assisi Parish Church',
      'town' => 'Talisay',
      'budget_low' => 'P500',
      'budget_high' => 'P1000',
      'best_months' => 'anytime you want Jan-Dec',
      'guide' => 'No',
      'permit' => 'No',
      'booking' => 'No',
      'hours' => 'Weekdays Daily Mass 6:00am and 6pm. Weekend Sat morning 5-6am and Sunday 6-8am and 4-6pm',
      'routes' => [
        [
          'origin' => 'Daet',
          'leg' => '1',
          'mode' => 'Jeep',
          'time' => '20m',
          'fare' => 'P15',
          'notes' => 'From the church walk into the highway there are jeep beside the BIR the last trip is 5pm but you van wait, because there are busses that stop to pick up passenger in the highway',
        ],
        [
          'origin' => 'Daet',
          'leg' => '1',
          'mode' => 'Motorcycle Private',
          'time' => '15m',
        ],
        [
          'origin' => 'Daet',
          'leg' => '1',
          'mode' => 'Bus',
          'time' => '20m',
          'fare' => 'P25',
          'notes' => 'From the church walk into the highway there are jeep beside the BIR the last trip is 5pm but you van wait, because there are busses that stop to pick up passenger in the highway',
        ],
      ],
      'fees' => [
        [],
      ],
      'contacts' => [
        [
          'org' => 'Cathedral',
          'phone' => '0917 135 5052',
          'email' => 'parishofficercbdstfrancis@gmail.com',
          'facebook' => 'https://www.facebook.com/p/St-Francis-of-Assisi-Parish-Talisay-Camarines-Norte-100076152849548/',
        ],
      ],
    ],
    [
      'name' => 'Calaguas Island',
      'town' => 'Vinzons',
      'best_months' => 'March to August',
      'guide' => 'No',
      'permit' => 'No',
      'booking' => 'No',
      'notes' => 'TWO JUMP-OFF PORTS: Paracale Fish Port, or Vinzons / Minaogan / Pajares Port and Tourist Hub. Do not assume all Calaguas boats leave from the same place - if an operator or resort names a port, use that one. Confirm before leaving Manila: which port is active, boat schedule, boat rate, weather, Coast Guard clearance, Calaguas Pass or registration requirement, and the return boat arrangement.',
      'routes' => [
        [
          'origin' => 'Manila (via Paracale)',
          'leg' => '1',
          'mode' => 'bus',
          'time' => '8h',
          'fare' => 'P515',
          'notes' => 'Superlines, Cubao or Alabang to Paracale/Daet. 7.5-8.5 hrs. Evening departure recommended so you arrive early.',
        ],
        [
          'origin' => 'Manila (via Paracale)',
          'leg' => '1',
          'mode' => 'bus',
          'time' => '10h',
          'fare' => 'P801',
          'notes' => 'DLTB, Cubao/Pasay/PITX to Daet. 8.5-11 hrs. Alternative operator for the same leg.',
        ],
        [
          'origin' => 'Manila (via Paracale)',
          'leg' => '1',
          'mode' => 'bus',
          'time' => '10h',
          'fare' => 'P350',
          'notes' => 'Non-aircon bus, PHP 300-400, 8.5-11 hrs. Alternative operator for the same leg.',
        ],
        [
          'origin' => 'Manila (via Paracale)',
          'leg' => '2',
          'mode' => 'van',
          'fare' => 'P100',
          'notes' => 'Daet to Paracale, PHP 50-150. If coming by bus, ask whether alighting at Talobatib Junction suits your route better.',
        ],
        [
          'origin' => 'Manila (via Paracale)',
          'leg' => '3',
          'mode' => 'boat',
          'time' => '2h 15m',
          'notes' => 'Paracale Fish Port to Mahabang Buhangin, 2-2.5 hrs. Fare not recorded. Weather dependent.',
        ],
        [
          'origin' => 'Manila (via Vinzons)',
          'leg' => '1',
          'mode' => 'bus',
          'time' => '8h',
          'fare' => 'P515',
          'notes' => 'Superlines to Daet. See the Paracale route for other operators and fares on this same leg.',
        ],
        [
          'origin' => 'Manila (via Vinzons)',
          'leg' => '2',
          'mode' => 'jeepney',
          'time' => '20m',
          'notes' => 'Daet to Vinzons, about 20 minutes. Jeep or tricycle, PHP 10-150 depending which you take.',
        ],
        [
          'origin' => 'Manila (via Vinzons)',
          'leg' => '3',
          'mode' => 'boat',
          'notes' => 'Vinzons / Minaogan / Pajares Port and Tourist Hub to Mahabang Buhangin. Duration and fare depend on whether it is a private charter or a public route with a secondary transfer. Weather dependent.',
        ],
        [
          'origin' => 'Daet',
          'leg' => '1',
          'mode' => 'van',
          'fare' => 'P100',
          'notes' => 'Daet to Paracale, PHP 50-150, if using the Paracale jump-off.',
        ],
        [
          'origin' => 'Daet',
          'leg' => '1',
          'mode' => 'jeepney',
          'time' => '20m',
          'notes' => 'Daet to Vinzons, about 20 minutes, PHP 10-150, if using the Vinzons jump-off.',
        ],
      ],
      'fees' => [
        [
          'label' => 'Boat, DIY',
          'amount' => 'P600',
          'unit' => 'per person',
          'asof' => 'supplied by site owner',
          'notes' => 'DIY boat, per person. Supplied by the site owner (revised down from an earlier PHP 800). Consistent with published accounts of splitting a charter: one group paid about PHP 700 each splitting PHP 3,500 five ways, another PHP 500 when merged with a second group.',
        ],
        [
          'label' => 'Boat charter, small',
          'amount' => 'P2500 to P3000',
          'unit' => 'per boat (4-6 pax)',
          'notes' => 'DESK RESEARCH, not confirmed. lakbaypinas.com 2026 guide, read Sept 2026. An older account (lakwatsero) gives PHP 3,000 for 5-6 pax overnight from Paracale.',
        ],
        [
          'label' => 'Boat charter, large',
          'amount' => 'P5000 to P6500',
          'unit' => 'per boat (about 20 pax)',
          'notes' => 'DESK RESEARCH, not confirmed. lakbaypinas.com 2026 guide, read Sept 2026.',
        ],
        [
          'label' => 'Boat, shared with another group',
          'amount' => 'P500',
          'unit' => 'per person',
          'notes' => 'DESK RESEARCH, not confirmed. rjdexplorer.com, about 9 months old. Paid when merged with other groups at Paracale.',
        ],
        [
          'label' => 'Environmental fee',
          'amount' => 'P20',
          'unit' => 'per person',
          'notes' => 'DESK RESEARCH. The most consistent figure found - PHP 20 appears in both a 2026 guide and an account from six years ago.',
        ],
        [
          'label' => 'Island / camp entrance',
          'amount' => 'P100 to P150',
          'unit' => 'per person',
          'notes' => 'DESK RESEARCH, not confirmed. Varies by campsite or resort. One older source also lists PHP 500 and PHP 95 depending on the resort, so this needs a local answer.',
        ],
        [
          'label' => 'Tent pitching',
          'amount' => 'P100',
          'unit' => 'per tent',
          'notes' => 'DESK RESEARCH, not confirmed. For DIY camping.',
        ],
        [
          'label' => 'Cottage, day use',
          'amount' => 'P300 to P500',
          'unit' => 'per cottage',
          'notes' => 'DESK RESEARCH, not confirmed.',
        ],
        [
          'label' => 'Cottage, overnight',
          'amount' => 'P500',
          'unit' => 'per cottage',
          'notes' => 'DESK RESEARCH, not confirmed.',
        ],
        [
          'label' => 'Shower',
          'amount' => 'P30',
          'unit' => 'per use',
          'notes' => 'DESK RESEARCH, not confirmed.',
        ],
        [
          'label' => 'Restroom',
          'amount' => 'P20',
          'unit' => 'per use',
          'notes' => 'DESK RESEARCH, not confirmed.',
        ],
        [
          'label' => 'Phone charging',
          'amount' => 'P50',
          'unit' => 'per device',
          'notes' => 'DESK RESEARCH, not confirmed. Power is generator-based, commonly 6PM-6AM.',
        ],
        [
          'label' => 'Trekking guide',
          'amount' => 'P50',
          'unit' => 'per person',
          'notes' => 'DESK RESEARCH, not confirmed. Local guide to the viewpoint.',
        ],
        [
          'label' => 'Paracale parking',
          'amount' => 'P200',
          'unit' => 'per vehicle',
          'notes' => 'DESK RESEARCH, not confirmed. Overnight rate at the fish port.',
        ],
        [
          'label' => 'Joiner tour, 2D1N, Vinzons meet-up',
          'amount' => 'P2499 to P2799',
          'unit' => 'per person',
          'notes' => 'DESK RESEARCH, private operators, NOT an endorsement. Range across operators is wide - other companies quote PHP 5,499 for the same 2D1N. Decide whether an official site should quote private rates at all.',
        ],
        [
          'label' => 'Joiner tour, 2D1N, with Manila transfers',
          'amount' => 'P3499 to P3999',
          'unit' => 'per person',
          'notes' => 'DESK RESEARCH, private operators, NOT an endorsement. See the note above.',
        ],
        [
          'label' => 'Joiner tour, 3D2N, with Manila transfers',
          'amount' => 'P4799 to P6499',
          'unit' => 'per person',
          'notes' => 'DESK RESEARCH, private operators, NOT an endorsement. See the note above.',
        ],
      ],
    ],
    [
      'name' => 'Mt. Panit',
      'town' => 'Vinzons',
      'budget_low' => 'P1000',
      'budget_high' => 'P2000',
      'best_months' => 'March to August',
      'guide' => 'No',
      'permit' => 'No',
      'booking' => 'No',
      'hours' => 'Nights',
      'notes' => 'Bring your own food and water cause there\'s no store nearby',
      'routes' => [
        [
          'origin' => 'Daet',
          'leg' => '1',
          'mode' => 'Motorcycle Private',
          'time' => '1h',
        ],
        [
          'origin' => 'Daet',
          'leg' => '1',
          'mode' => 'Jeep Double Ride',
          'time' => '2h',
          'fare' => 'P75',
          'notes' => '8am First Trip if you are in labo to mt.panit and no other jeep the next trip is 5pm',
        ],
        [
          'origin' => 'Daet',
          'leg' => '4',
          'mode' => '4Wheels (Car,Van),',
          'time' => '45m',
          'notes' => 'The road in Mt.panit is to narrow for 4wheels',
        ],
      ],
      'fees' => [
        [
          'asof' => '2026-09-03',
          'notes' => 'no entrance fee',
        ],
        [
          'label' => 'Parking',
          'amount' => 'P20',
          'unit' => 'per vehicle',
          'asof' => '2026-09-03',
          'notes' => 'local parking charge',
        ],
        [
          'label' => 'Tourguide',
          'amount' => 'P300',
          'unit' => 'per group',
          'asof' => '2026-09-03',
          'notes' => 'may vary depending on froup/trip',
        ],
      ],
      'contacts' => [
        [
          'org' => 'Vinzons Municipal Tourism Office',
          'phone' => '0908-889-4116',
          'email' => 'lgu.vinzons.2016@gmail.com',
          'facebook' => 'facebook.com/vinzonstourism',
        ],
      ],
    ],
  ],

  'festivals' => [
    [
      'name' => 'Paruyan Festival',
      'town' => 'Talisay',
      'kind' => 'harvest',
      'about' => 'Amateur Singing Competition, Miss Talisay, Fun- Run, Agri-Tourism fair, Beer Plaza through the town',
      'timing' => '1st week of October',
      'month' => '10',
      'dates' => [
        [
          'start' => '2026-09-09',
          'end' => '2026-10-04',
          'status' => 'Announced',
        ],
      ],
      'contacts' => [
        [
          'org' => 'Talisay Municipal Tourism Office',
          'phone' => '0961-588-8216',
          'email' => 'lgutalisay@gmail.com',
          'facebook' => 'facebook.com/p/Paruyan-Festival',
        ],
      ],
    ],
    [
      'name' => 'Babakasin Festival',
      'town' => 'Vinzons',
      'kind' => 'Foods',
      'about' => 'Grand Parades & Street Dancing, Battle of the Festival Queen, Cosplay Competition, Musical Competition, Trades Fair through the town',
      'timing' => 'last week of June',
      'month' => '6',
    ],
    [
      'name' => 'Rahugan Festival',
      'town' => 'Basud, Camarines Norte',
      'kind' => 'Cultural / community festival',
      'about' => 'The festival showcases the culture, traditions, beliefs, and community character of Basud. Activities have included the Grand Rahugan Parade, Bikol Folksong Singing Competition, street dancing, cultural activities, sports/laro ng lahi, agro-tourism activities, and other community events.',
      'timing' => 'October 17–24',
      'month' => 'October',
      'contacts' => [
        [
          'org' => 'Office of the Mayor, Municipality of Basud',
          'phone' => '(054) 443-1017',
          'email' => 'lgubasud16@gmail.com',
          'facebook' => 'facebook.com/profile.php?id=61563281673069',
        ],
      ],
    ],
    [
      'name' => 'Palong Festival',
      'town' => 'Capalonga',
      'kind' => 'Cultural / civic / agro-industrial / street-dancing festival',
      'about' => 'The festival features street dancing and an agro-industrial fair. It celebrates Capalonga\'s name and the local abundance of palong manok/cockscomb, while also coinciding with the Black Nazarene Feast Day on May 13.',
      'timing' => 'May 11–13',
      'month' => 'May',
      'contacts' => [
        [
          'org' => 'Municipal Government of Capalonga / Capalonga Tourism Office',
          'phone' => '0920 928 8167',
          'email' => 'jesusbnc2009@gmail.com',
          'facebook' => 'facebook.com/blacknazareneofcapalonga',
        ],
      ],
    ],
    [
      'name' => 'Black Nazarene Feast',
      'town' => 'Capalonga, Camarines Norte',
      'kind' => 'Religious feast / pilgrimage',
      'about' => 'Masses, religious processions, prayers, novenas, veneration of the Black Nazarene and pilgrimage activities.',
      'timing' => 'May 12–13',
      'month' => 'May',
      'dates' => [
        [
          'year' => '2026',
          'start' => '2026-05-12',
          'end' => '2026-05-13',
          'status' => 'Annual',
        ],
      ],
    ],
    [
      'name' => 'Pinyasan Festival',
      'town' => 'Daet, Camarines Norte',
      'kind' => 'Cultural / agricultural / food / tourism festival',
      'about' => 'Celebrates Daet\'s famous Formosa Queen Pineapple. Activities include float exhibitions, street dancing, agro-industrial/trade fairs, cultural shows, sports, talent and skills competitions, concerts and other community activities.',
      'timing' => 'June 15–24',
      'month' => 'June',
      'dates' => [
        [
          'year' => '2026',
          'start' => '2026-06-15',
          'end' => '2026-06-24',
          'status' => 'Expected',
        ],
      ],
      'contacts' => [
        [
          'org' => 'Municipality of Daet / Municipal Tourism Office',
          'phone' => '0962 175 4431',
          'email' => 'cometocamnorte@gmail.com',
          'facebook' => 'facebook.com/CamNorteTourism',
        ],
      ],
    ],
    [
      'name' => 'Bantayog Festival',
      'town' => 'Daet, Camarines Norte',
      'kind' => 'Historical / cultural / provincial foundation festival',
      'about' => 'The First Rizal Monument is the centerpiece of the celebration. Activities commemorate the province\'s history, foundation and heritage and can include cultural presentations, parades, sports, outdoor activities and other provincial events.',
      'timing' => 'March–May, depending on the annual program',
      'month' => 'April',
      'dates' => [
        [
          'year' => '2026',
          'start' => '2026-04-05',
          'end' => '2026-05-17',
          'status' => 'Announced',
        ],
      ],
      'contacts' => [
        [
          'org' => 'Provincial Government of Camarines Norte / Provincial Tourism Operations Division',
          'phone' => '(054) 721-3087',
          'email' => 'cometocamnorte@gmail.com',
          'facebook' => 'facebook.com/CamNorteTourism',
        ],
      ],
    ],
    [
      'name' => 'Mambulawan Festival',
      'town' => 'Jose Panganiban, Camarines Norte',
      'kind' => 'Cultural / community / religious / town fiesta festival',
      'about' => 'The festival coincides with the Feast of Our Lady of the Most Holy Rosary and promotes community unity, culture and arts, and local economic development. Historical descriptions also identify activities such as street dancing, cultural presentations, sports, trade/agri-fishery activities and religious events.',
      'timing' => 'October 6–7',
      'month' => 'October',
      'dates' => [
        [
          'year' => '2026',
          'start' => '2026-10-06',
          'end' => '2026-10-07',
          'status' => 'Expected',
        ],
      ],
      'contacts' => [
        [
          'org' => 'Jose Panganiban Municipal Tourism Office / LGU Jose Panganiban',
          'phone' => '0963-025-9024',
          'email' => 'tourismjpang@gmail.com',
          'facebook' => 'facebook.com/profile.php?id=61568113830387',
        ],
      ],
    ],
    [
      'name' => 'Pabirik Festival',
      'town' => 'Paracale',
      'kind' => 'cultural',
      'about' => 'Gold-panning heritage festival. "Pabirik" is the pan used to wash gold from river sand.',
      'timing' => 'late January into early February',
      'month' => '1',
    ],
    [
      'name' => 'Kadagatan Festival',
      'town' => 'Mercedes',
      'kind' => 'cultural',
      'about' => 'Coastal and fishing festival. "Kadagatan" means the sea; it celebrates the town fishing traditions.',
      'timing' => 'August',
      'month' => '8',
    ],
    [
      'name' => 'Busig-on Festival',
      'town' => 'Labo',
      'kind' => 'cultural',
      'timing' => 'September',
      'month' => '9',
    ],
    [
      'name' => 'Boyuboy Festival',
      'town' => 'San Lorenzo Ruiz',
      'kind' => 'cultural',
    ],
    [
      'name' => 'Mananap Festival',
      'town' => 'San Vicente',
      'kind' => 'cultural',
    ],
    [
      'name' => 'Palayog Festival',
      'town' => 'Santa Elena',
      'kind' => 'cultural',
    ],
  ],
];